name: "Hailo LLM"
version: "1.0.0"
slug: "hailo_llm"
description: "Hailo-10H + Model Zoo + Ollama LLM server"
url: "https://github.com/bjorngluck/hailo-llm-addon"
arch:
  - aarch64
init: false
privileged: true
map:
  - share:rw
options:
  keep_alive: "5m"
schema:
  keep_alive: str
ports:
  8000/tcp: 8000